name: Hostlist Compiler Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm install -g @adguard/hostlist-compiler
          hostlist-compiler -c ./data/configuration.json -o ./rules.txt
          python ./data/Update-readme-rules.py
      - uses: stefanzweifel/git-auto-commit-action@v6
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 0
